language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nFAmQvPNmoZ9Z5KwuZlTyoG1CwpgtVBBhXimMyXxCfSCGe0NWUpqAd7WpN3ikOQbk2lpD8woqtIVpVDXopLJjsKrNIWu2+dKFaeywuPr9JaSA0i4aBdbDZVrnbrvhMj670MbkhvYZqfUWBjebsZuDSWzAxAgMhdHbT46fSSni23a5BkRaIaqI9cJfFw3maot0PRezC7qUYhqD/QgByjxsZ90IqxBeYQGTUHBFh2pvi6eJRkc4hwi4JsEYXYCzpsblBBoK8/sjgbosNkSLJn09C0B0nKCQPyPJncIBHfdWFkZhD3Ka3lVTV6ZUSHyr0Gn98Bu9xmikxuussGoMjTl/aJwk7Cyao1yZxQ4XotE977MxTDggzpiKZU2Z4wrkrXRDDkjAYXQtyTVdgT28h7wIUlxv7WAaMlIX+J8LncSkEidDqr7uB1u8WzFpMMloV8zRQK6vX61w0UACZeg/sJZqtS3XU50q2GVqEB32FtFAb+tfbB9vOvpuZnOsyQUnTWE0ccSh92keGsg42FDUdmMJNU+8y0/iUaiQL/Bezvbk9Z2FhbNGpAuXrtEiRO9RX88PBl62sbvYNfhjReLYvE2VomKyeQx/eoN7bsmZ4bqVsEallklhk1kBtygIwS0tGUpFi505Gn12b7AA3RVYaM7rRwaLPGCMUp9JHQnj5QUypg=
  app: https://limitless-hamlet-48508.herokuapp.com/
  on:
    repo: Thinkful-Ed/node-restaurants-app-mongoose
